extends:
  import: classic
  file: go/pipeline.yaml
pipelines:
  default:
    options:
      volumes:
      - name: docker-daemon
        hostPath:
          path: /var/run/docker.sock
  pullRequest:
    build:
      steps:
      - sh: docker build -f /workspace/source/Dockerfile --tag $DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION /workspace/source
        image: docker:stable
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-daemon
    promote:
      steps:
      - dir: /home/jenkins/go/src/REPLACE_ME_GIT_PROVIDER/REPLACE_ME_ORG/REPLACE_ME_APP_NAME/charts/preview
        steps:
        - sh: make preview
          name: make-preview
          image: gcr.io/jenkinsxio/builder-go
        - sh: jx preview --app $APP_NAME --dir ../..
          name: jx-preview
          image: gcr.io/jenkinsxio-labs-private/jx-cli

  release:
    build:
      steps:
      - sh: docker build -f /workspace/source/Dockerfile --tag $DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION /workspace/source
        image: docker:stable
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-daemon
    promote:
      steps:
      - dir: /home/jenkins/go/src/REPLACE_ME_GIT_PROVIDER/REPLACE_ME_ORG/REPLACE_ME_APP_NAME/charts/REPLACE_ME_APP_NAME
        steps:
        - sh: jx step changelog --version v\$(cat ../../VERSION)
          name: changelog
          image: gcr.io/jenkinsxio-labs-private/jxl
        - comment: release the helm chart
          name: helm-release
          image: gcr.io/jenkinsxio-labs-private/jxl
          sh: jx step helm release
        - comment: promote through all 'Auto' promotion Environments
          sh: jx promote -b --all-auto --timeout 1h
          name: jx-promote
          image: gcr.io/jenkinsxio-labs-private/jx-cli
    setVersion:
      steps:
      - sh: jx step next-version --use-git-tag-only
        name: next-version
        image: gcr.io/jenkinsxio-labs-private/jxl
        comment: so we can retrieve the version in later steps
      - sh: jx step tag --version \$(cat VERSION) --no-apply
        image: gcr.io/jenkinsxio-labs-private/jxl
        name: update-version
      - sh: "echo disabled: jx gitops helm template --optional"
        name: helm-template
        image: gcr.io/jenkinsxio-labs-private/jx-cli
        comment: lets release the versioned kubernetes resources for consumption via kubectl/kpt/kustomize
      - sh: jx step tag --version \$(cat VERSION)
        image: gcr.io/jenkinsxio-labs-private/jxl
        name: tag-version
